hayden_songs = [
        {
            'name': "Chery coloured Funk",
            'album_id': 1,
            'track_number': 1,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Cherry+coloured+Funk+-+1.mp3",
            'song_length': 193,
        },
        {
            'name': "Pitch the Baby",
            'album_id': 1,
            'track_number': 2,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Pitch+the+Baby+-+2.mp3",
            'song_length': 194,
        },
        {
            'name': "Iceblink Luck",
            'album_id': 1,
            'track_number': 3,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Iceblink+Luck+-+3.mp3",
            'song_length': 197,
        },
        {
            'name': "Fifty-fifty Clown",
            'album_id': 1,
            'track_number': 4,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fifty-fifty+Clown+-+4.mp3",
            'song_length': 190,
        },
        {
            'name': "Heaven Or Las Vegas",
            'album_id': 1,
            'track_number': 5,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Heaven+Or+Las+Vegas+-+5.mp3",
            'song_length': 231,
        },
        {
            'name': "I Wear Your Ring",
            'album_id': 1,
            'track_number': 6,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+Wear+Your+Ring+-+6.mp3",
            'song_length': 209,
        },
        {
            'name': "Fotzepolitic",
            'album_id': 1,
            'track_number': 7,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fotzepolitic+-+7.mp3",
            'song_length': 211,
        },
        {
            'name': "Wolf in the Breast",
            'album_id': 1,
            'track_number': 8,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Wolf+in+the+Breast+-+8.mp3",
            'song_length': 211,
        },
        {
            'name': "Road, River and Rail",
            'album_id': 1,
            'track_number': 9,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Road%2C+River+and+Rail+-+9.mp3",
            'song_length': 201,
        },
        {
            'name': "Frou-frou Foxes in Midsummer Fires",
            'album_id': 1,
            'track_number': 10,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            'song_length': 338,
        },
        {
            'name': "IGOR'S THEME",
            'album_id': 2,
            'track_number': 1,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/IGOR'S+THEME+-+1.mp3",
            'song_length': 200,
        },
        {
            'name': "EARFQUAKE",
            'album_id': 2,
            'track_number': 2,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/EARFQUAKE+-+2.mp3",
            'song_length': 190,
        },
        {
            'name': "I THINK",
            'album_id': 2,
            'track_number': 3,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+THINK+-+3.mp3",
            'song_length': 212,
        },
        {
            'name': "EXACTLY WHAT YOU RUN FROM YOU END UP CHASING",
            'album_id': 2,
            'track_number': 4,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/EXACTLY+WHAT+YOU+RUN+FROM+YOU+END+UP+CHASING+-+4.mp3",
            'song_length': 14,
        },
        {
            'name': "RUNNING OUT OF TIME",
            'album_id': 2,
            'track_number': 5,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/RUNNING+OUT+OF+TIME+-+5.mp3",
            'song_length': 177,
        },
        {
            'name': "NEW MAGIC WAND",
            'album_id': 2,
            'track_number': 6,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/NEW+MAGIC+WAND+-+6.mp3",
            'song_length': 195,
        },
        {
            'name': "A BOY IS A GUN",
            'album_id': 2,
            'track_number': 7,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/A+BOY+IS+A+GUN+-+7.mp3",
            'song_length': 210,
        },
        {
            'name': "PUPPET",
            'album_id': 2,
            'track_number': 8,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/PUPPET+-+8.mp3",
            'song_length': 179,
        },
        {
            'name': "WHAT'S GOOD",
            'album_id': 2,
            'track_number': 9,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/WHAT'S+GOOD+-+9.mp3",
            'song_length': 205,
        },
        {
            'name': "GONE GONE / THANK YOU",
            'album_id': 2,
            'track_number': 10,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/GONE%2C+GONE+_+THANK+YOU+-+10.mp3",
            'song_length': 375,
        },
        {
            'name': "I DON'T LOVE YOU ANYMORE",
            'album_id': 2,
            'track_number': 11,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+DON'T+LOVE+YOU+ANYMORE+-+11.mp3",
            'song_length': 161,
        },
        {
            'name': "ARE WE STILL FRIENDS",
            'album_id': 2,
            'track_number': 12,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/ARE+WE+STILL+FRIENDS+-+12.mp3",
            'song_length': 245,
        },
        {
            'name': "Watch out for Golem",
            'album_id': 3,
            'track_number': 1,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/1+-+Watch+out+for+Golem..mp3",
            'song_length': 104,
        },
        {
            'name': "Felt Good",
            'album_id': 3,
            'track_number': 2,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/2+-+Felt+Good.mp3",
            'song_length': 129,
        },
        {
            'name': "Bliss",
            'album_id': 3,
            'track_number': 3,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/3+-+Bliss.mp3",
            'song_length': 110,
        },
        {
            'name': "Untouchable",
            'album_id': 3,
            'track_number': 4,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/4+-+Untouchable.mp3",
            'song_length': 130,
        },
        {
            'name': "Spiritual Realm",
            'album_id': 3,
            'track_number': 5,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/5+-+Spiritual+Realm.mp3",
            'song_length': 91,
        },
        {
            'name': "Villfarelse",
            'album_id': 3,
            'track_number': 6,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/6+-+Villfarelse.mp3",
            'song_length': 128,
        },
        {
            'name': "Polliwogs",
            'album_id': 3,
            'track_number': 7,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/7+-+Polliwogs.mp3",
            'song_length': 153,
        },
        {
            'name': "Ant Racing",
            'album_id': 3,
            'track_number': 8,
            'audio_url': "https://moodifybucket.s3.us-east-2.amazonaws.com/Hazardous+Bubble+Basics/8+-+Ant+Racing.mp3",
            'song_length': 88,
        },
    ]
