mira_songs = [
        {
            "name": "Sweet Head",
            "album_id": 4,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Sweet+Head+(Previously+unreleased+outtake+from+November+1971+album+session)++David+Bowie.mp3",
            "song_length": 258,
        },
        {
            "name": "John, I'm Only Dancing",
            "album_id": 4,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/John%2C+I'm+Only+Dancing+(2012+Remaster).mp3",
            "song_length": 165,
        },
        {
            "name": "Rock 'n' Roll Suicide",
            "album_id": 4,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Rock+'n'+Roll+Suicide+(2012+Remaster).mp3",
            "song_length": 175,
        },
        {
            "name": "Suffragette City",
            "album_id": 4,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Suffragette+City+(2012+Remaster).mp3",
            "song_length": 201,
        },
        {
            "name": "Ziggy Stardust ",
            "album_id": 4,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Ziggy+Stardust+(2012+Remaster).mp3",
            "song_length": 192,
        },
        {
            "name": "Hang on to Yourself",
            "album_id": 4,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Hang+on+to+Yourself+(2012+Remaster).mp3",
            "song_length": 159,
        },
        {
            "name": "Star",
            "album_id": 4,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Star+(2012+Remaster).mp3",
            "song_length": 167,
        },
        {
            "name": "Lady Stardust",
            "album_id": 4,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Lady+Stardust+(2012+Remaster).mp3",
            "song_length": 210,
        },
        {
            "name": "It Ain't Easy",
            "album_id": 4,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/It+Ain't+Easy+(2012+Remaster).mp3",
            "song_length": 174,
        },
        {
            "name": "Starman",
            "album_id": 4,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Starman+(2012+Remaster).mp3",
            "song_length": 253,
        },
        {
            "name": "Moonage Daydream ",
            "album_id": 4,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Moonage+Daydream+(2012+Remaster).mp3",
            "song_length": 278,
        },
        {
            "name": "Soul Love",
            "album_id": 4,
            "track_number": 12,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Soul+Love+(2012+Remaster).mp3",
            "song_length": 212,
        },
        {
            "name": "Five Years",
            "album_id": 4,
            "track_number": 13,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/Five+Years+(2012+Remaster).mp3",
            "song_length": 283,
        },
        {
            "name": "David Bowie Is - Nile Rodgers",
            "album_id": 4,
            "track_number": 14,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/DavidBowie-Ziggy-Stardust/David+Bowie+Is+-+Nile+Rodgers.mp3",
            "song_length": 135,
        },
        {
            "name": "Inténtalo",
            "album_id": 5,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/Inte%CC%81ntalo+-+MTZ+Manuel+Turizo++Visualizer+(1).mp3",
            "song_length": 163,
        },
        {
            "name": "Guayabo",
            "album_id": 5,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/Guayabo+-+MTZ+Manuel+Turizo++Visualizer.mp3",
            "song_length": 165,
        },
        {
            "name": "U La La",
            "album_id": 5,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/U+La+La+-+MTZ+Manuel+Turizo++Visualizer.mp3",
            "song_length": 152,
        },
        {
            "name": "Jamaica",
            "album_id": 5,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/Jamaica++MTZ+Manuel+Turizo+x+Bee%CC%81le++Video+Lyric.mp3",
            "song_length": 190,
        },
        {
            "name": "El Merengue",
            "album_id": 5,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/El+Merengue+-+Marshmello+x+MTZ+Manuel+Turizo++Video+Lyric.mp3",
            "song_length": 188,
        },
        {
            "name": "Triste",
            "album_id": 5,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/Triste+-+MTZ+Manuel+Turizo++Visualizer.mp3",
            "song_length": 223,
        },
        {
            "name": "No Te Sientes Igual",
            "album_id": 5,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Album-2000-songs/No+Te+Sientes+Igual+-+MTZ+Manuel+Turizo++Visualizer.mp3",
            "song_length": 181,
        },
        {
            "name": "Mermaid",
            "album_id": 6,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Mermaid+(Audio).mp3",
            "song_length": 263,
        },
        {
            "name": "Bullet Proof Soul ",
            "album_id": 6,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Bullet+Proof+Soul+(Audio).mp3",
            "song_length": 325,
        },
        {
            "name": "Pearls",
            "album_id": 6,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Pearls+(Audio).mp3",
            "song_length": 274,
        },
        {
            "name": "Cherish The Day",
            "album_id": 6,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Cherish+The+Day+-+Official+-+1993.mp3",
            "song_length": 263,
        },
        {
            "name": "Kiss Of Life",
            "album_id": 6,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Kiss+Of+Life+-+Official+-+1993.mp3",
            "song_length": 251,
        },
        {
            "name": "Like a Tattoo ",
            "album_id": 6,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Like+a+Tattoo+(Audio).mp3",
            "song_length": 221,
        },
        {
            "name": "I Couldn't Love You More ",
            "album_id": 6,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+I+Couldn't+Love+You+More+(Audio).mp3",
            "song_length": 228,
        },
        {
            "name": " Feel No Pain",
            "album_id": 6,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+Feel+No+Pain+-+Official+-+1992.mp3",
            "song_length": 227,
        },
        {
            "name": "No Ordinary Love",
            "album_id": 6,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Love+Deluxe-songs/Sade+-+No+Ordinary+Love+-+Official+-+1992.mp3",
            "song_length": 241,
        },
    ]
