alex_songs = [
        {
            "name": "Rehab",
            "album_id": 7,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Cherry+coloured+Funk+-+1.mp3",
            "song_length": 213,
        },
        {
            "name": "You Know I'm No Good",
            "album_id": 7,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Pitch+the+Baby+-+2.mp3",
            "song_length": 257,
        },
        {
            "name": "Me & Mr Jones",
            "album_id": 7,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Iceblink+Luck+-+3.mp3",
            "song_length": 153,
        },
        {
            "name": "Just Friends",
            "album_id": 7,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fifty-fifty+Clown+-+4.mp3",
            "song_length": 193,
        },
        {
            "name": "Back To Black",
            "album_id": 7,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Heaven+Or+Las+Vegas+-+5.mp3",
            "song_length": 241,
        },
        {
            "name": "Love Is A Losing Game",
            "album_id": 7,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+Wear+Your+Ring+-+6.mp3",
            "song_length": 154,
        },
        {
            "name": "Tears Dry On Their Own",
            "album_id": 7,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fotzepolitic+-+7.mp3",
            "song_length": 186,
        },
        {
            "name": "Wake up Alone",
            "album_id": 7,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Wolf+in+the+Breast+-+8.mp3",
            "song_length": 221,
        },
        {
            "name": "Some Unholy War",
            "album_id": 7,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Road%2C+River+and+Rail+-+9.mp3",
            "song_length": 141,
        },
        {
            "name": "He Can Only Hold Her",
            "album_id": 7,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 164,
        },
        {
            "name": "Addicted",
            "album_id": 7,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 165,
        },
        {
            "name": "A Pain That I'm Used To",
            "album_id": 8,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Cherry+coloured+Funk+-+1.mp3",
            "song_length": 250,
        },
        {
            "name": "John the Revelator",
            "album_id": 8,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Pitch+the+Baby+-+2.mp3",
            "song_length": 221,
        },
        {
            "name": "Suffer Well",
            "album_id": 8,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Iceblink+Luck+-+3.mp3",
            "song_length": 229,
        },
        {
            "name": "The Sinner in Me",
            "album_id": 8,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fifty-fifty+Clown+-+4.mp3",
            "song_length": 295,
        },
        {
            "name": "Precious",
            "album_id": 8,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Heaven+Or+Las+Vegas+-+5.mp3",
            "song_length": 245,
        },
        {
            "name": "Macro",
            "album_id": 8,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+Wear+Your+Ring+-+6.mp3",
            "song_length": 242,
        },
        {
            "name": "I Want It All",
            "album_id": 8,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fotzepolitic+-+7.mp3",
            "song_length": 369,
        },
        {
            "name": "Nothing's Impossible",
            "album_id": 8,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Wolf+in+the+Breast+-+8.mp3",
            "song_length": 261,
        },
        {
            "name": "Introspectre",
            "album_id": 8,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Road%2C+River+and+Rail+-+9.mp3",
            "song_length": 102,
        },
        {
            "name": "Damaged People",
            "album_id": 8,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 207,
        },
        {
            "name": "Lilian",
            "album_id": 8,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 285,
        },
        {
            "name": "The Darkest Star",
            "album_id": 8,
            "track_number": 12,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 415,
        },
        {
            "name": "Eppur Si Muove",
            "album_id": 9,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Cherry+coloured+Funk+-+1.mp3",
            "song_length": 221,
        },
        {
            "name": "Feel Me Heaven",
            "album_id": 9,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Pitch+the+Baby+-+2.mp3",
            "song_length": 290,
        },
        {
            "name": "Dreaming Of Andromeda",
            "album_id": 9,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Iceblink+Luck+-+3.mp3",
            "song_length": 266,
        },
        {
            "name": "Dancing With Mephisto",
            "album_id": 9,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fifty-fifty+Clown+-+4.mp3",
            "song_length": 265,
        },
        {
            "name": "Northern Lights",
            "album_id": 9,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Heaven+Or+Las+Vegas+-+5.mp3",
            "song_length": 220,
        },
        {
            "name": "Invisible Love",
            "album_id": 9,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/I+Wear+Your+Ring+-+6.mp3",
            "song_length": 295,
        },
        {
            "name": "Message From lo",
            "album_id": 9,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Fotzepolitic+-+7.mp3",
            "song_length": 190,
        },
        {
            "name": "Hello And Welcome",
            "album_id": 9,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Wolf+in+the+Breast+-+8.mp3",
            "song_length": 308,
        },
        {
            "name": "20,000 Miles Over The Sea",
            "album_id": 9,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Road%2C+River+and+Rail+-+9.mp3",
            "song_length": 263,
        },
        {
            "name": "Sitting On The Moon",
            "album_id": 9,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 308,
        },
        {
            "name": "The Alchemist",
            "album_id": 9,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 281,
        },
        {
            "name": "Goodbye Milky Way",
            "album_id": 9,
            "track_number": 12,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/songs/Frou-frou+Foxes+in+Midsummer+Fires+-10.mp3",
            "song_length": 358,
        },

    ]
