alex_songs = [
        {
            "name": "Rehab",
            "album_id": 7,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/1-Rehab.mp3",
            "song_length": 213,
        },
        {
            "name": "You Know I'm No Good",
            "album_id": 7,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/2-You+Know+I'm+No+Good.mp3",
            "song_length": 257,
        },
        {
            "name": "Me & Mr Jones",
            "album_id": 7,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/3-Me+%26+Mr+Jones.mp3",
            "song_length": 153,
        },
        {
            "name": "Just Friends",
            "album_id": 7,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/4-Just+Friends.mp3",
            "song_length": 193,
        },
        {
            "name": "Back To Black",
            "album_id": 7,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/5-Back+To+Black.mp3",
            "song_length": 241,
        },
        {
            "name": "Love Is A Losing Game",
            "album_id": 7,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/6-Love+Is+A+Losing+Game.mp3",
            "song_length": 154,
        },
        {
            "name": "Tears Dry On Their Own",
            "album_id": 7,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/7-Tears+Dry+On+Their+Own.mp3",
            "song_length": 186,
        },
        {
            "name": "Wake up Alone",
            "album_id": 7,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/8-Wake+Up+Alone.mp3",
            "song_length": 221,
        },
        {
            "name": "Some Unholy War",
            "album_id": 7,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/9-Some+Unholy+War.mp3",
            "song_length": 141,
        },
        {
            "name": "He Can Only Hold Her",
            "album_id": 7,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/10-He+Can+Only+Hold+Her.mp3",
            "song_length": 164,
        },
        {
            "name": "Addicted",
            "album_id": 7,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Amy+Winehouse+-+Back+to+Black+-2006+released/11-Addicted.mp3",
            "song_length": 165,
        },
        {
            "name": "A Pain That I'm Used To",
            "album_id": 8,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/1-A+Pain+That+I'm+Used+To.mp3",
            "song_length": 250,
        },
        {
            "name": "John the Revelator",
            "album_id": 8,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/2-John+the+Revelator.mp3",
            "song_length": 221,
        },
        {
            "name": "Suffer Well",
            "album_id": 8,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/3-Suffer+Well.mp3",
            "song_length": 229,
        },
        {
            "name": "The Sinner in Me",
            "album_id": 8,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/4-The+Sinner+in+Me.mp3",
            "song_length": 295,
        },
        {
            "name": "Precious",
            "album_id": 8,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/5-Precious.mp3",
            "song_length": 245,
        },
        {
            "name": "Macro",
            "album_id": 8,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/6-Macro.mp3",
            "song_length": 242,
        },
        {
            "name": "I Want It All",
            "album_id": 8,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/7-I+Want+It+All.mp3",
            "song_length": 369,
        },
        {
            "name": "Nothing's Impossible",
            "album_id": 8,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/8-Nothing's+Impossible.mp3",
            "song_length": 261,
        },
        {
            "name": "Introspectre",
            "album_id": 8,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/9-Introspectre.mp3",
            "song_length": 102,
        },
        {
            "name": "Damaged People",
            "album_id": 8,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/10-Damaged+People.mp3",
            "song_length": 207,
        },
        {
            "name": "Lilian",
            "album_id": 8,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/11-Lilian.mp3",
            "song_length": 285,
        },
        {
            "name": "The Darkest Star",
            "album_id": 8,
            "track_number": 12,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Depeche+Mode+-+Playing+The+Angel+-2005+released/12-The+Darkest+Star.mp3",
            "song_length": 415,
        },
        {
            "name": "Eppur Si Muove",
            "album_id": 9,
            "track_number": 1,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/1-Eppur+Si+Muove.mp3",
            "song_length": 221,
        },
        {
            "name": "Feel Me Heaven",
            "album_id": 9,
            "track_number": 2,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/2-Feel+Me+Heaven.mp3",
            "song_length": 290,
        },
        {
            "name": "Dreaming Of Andromeda",
            "album_id": 9,
            "track_number": 3,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/3-Dreaming+Of+Andromeda.mp3",
            "song_length": 266,
        },
        {
            "name": "Dancing With Mephisto",
            "album_id": 9,
            "track_number": 4,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/4-Dancing+With+Mephisto.mp3",
            "song_length": 265,
        },
        {
            "name": "Northern Lights",
            "album_id": 9,
            "track_number": 5,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/5-Northern+Lights.mp3",
            "song_length": 220,
        },
        {
            "name": "Invisible Love",
            "album_id": 9,
            "track_number": 6,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/6-Invisible+Love.mp3",
            "song_length": 295,
        },
        {
            "name": "Message From Io",
            "album_id": 9,
            "track_number": 7,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/7-Message+From+Io.mp3",
            "song_length": 190,
        },
        {
            "name": "Hello And Welcome",
            "album_id": 9,
            "track_number": 8,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/8-Hello+And+Welcome+(New+Version).mp3",
            "song_length": 308,
        },
        {
            "name": "20,000 Miles Over The Sea",
            "album_id": 9,
            "track_number": 9,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/9-20%2C000+Miles+Over+The+Sea.mp3",
            "song_length": 263,
        },
        {
            "name": "Sitting On The Moon",
            "album_id": 9,
            "track_number": 10,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/10-Sitting+On+The+Moon.mp3",
            "song_length": 308,
        },
        {
            "name": "The Alchemist",
            "album_id": 9,
            "track_number": 11,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/11-The+Alchemist.mp3",
            "song_length": 281,
        },
        {
            "name": "Goodbye Milky Way",
            "album_id": 9,
            "track_number": 12,
            "audio_url": "https://moodifybucket.s3.us-east-2.amazonaws.com/Enigma+-+A+Posteriori+-+2006/12-Goodbye+Milky+Way.mp3",
            "song_length": 358,
        },

    ]
